<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.secure-chat</groupId>
        <artifactId>secure-chat-parent</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>db-connection</artifactId>

    <build>
        <sourceDirectory>main</sourceDirectory>
        <testSourceDirectory>tests</testSourceDirectory>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
    </dependencies>
</project>